HTTP_OK = 200
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_UNPROCESSABLE_ENTITY = 422
HTTP_INTERNAL_ERROR = 500

BUSINESS_STATUS = {
    'success': 0,
    'partial_success': 1,
    'failed': -1,
}
